name = "dgc_procu"
main = "src/index.js"
compatibility_date = "2024-05-24"

[triggers]
crons = [ "0 1 * * 1-5" ]  # Monday to Friday at 9:00 AM Taiwan Time (1:00 AM UTC)

[[d1_databases]]
binding = "DB"
database_name = "dgc_procu-db"
database_id = "cec70333-e8d1-486d-9b53-e87065aa1590"

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true
